Project build setup, cgo extension
spacemeshos/go-svm-old pull request #8
Opened 2020-05-06 20:01 UTC by moshababo

### WIP.

TODO:
- [x] Project build setup
- [x] cgo extensions + tests
- [ ] bridge functionalities
...

2020-05-25 16:38 UTC, YaronWittenstein requested changes

2020-05-25 16:38 UTC, YaronWittenstein commented on README.md
> +To allow direct and seamless import of the Go package, it includes the pre-compiled binaries mentioned above, which will be continuously updated. It *currently* supports only macOS x86_64.
maybe we could use this API:
https://developer.github.com/v3/actions/artifacts/#download-an-artifact

instead of storing the binaries inside the repository?

This should not be a blocker for this PR - what do you think about this in general?

2020-05-25 16:38 UTC, YaronWittenstein commented on examples/counter/counter.go
> +// The first argument is the runtime context, and must be included by all import functions.
just noting that I'm believe the `ctx` is optional

2020-05-25 16:38 UTC, YaronWittenstein commented on examples/counter/counter.go
> +	pageCount int,
this will have to change for the new `DataLayout`

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/value.go
> +type ValueType int
can it be `byte / uint8` ?

2020-05-25 16:38 UTC, YaronWittenstein commented on svm-dep/Cargo.toml
> +
please add:

```toml
publish = false
```

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/doc.go
> +// [SVM] is a smart contracts framework written in [Rust].
I think we need to add credits to [`go-ext-wasm`](https://github.com/wasmerio/go-ext-wasm).

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/host_ctx.go
> +	panic("not implemented")
...

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/import.go
> +	wasmInputs ValueTypes
I'd prefer to use: `args` or `funcArgs`

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/import.go
> +	wasmOutputs ValueTypes
I prefer to use `returns` or `funcReturns / funcRets`

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/import.go
> +	wasmInputs, wasmOutputs, err := validateImport(name, implementation)
I'd rename to:

```go
args, returns, err := validateImport(name, implementation)
```

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/kv.go
> +func NewMemoryKVStore() (unsafe.Pointer, error) {
after adapting to the new SVM storage layer - I think that this one will become redundant.

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/value_test.go
> +func TestValues_Encode_Decode(t *testing.T) {
it seems there a couple of mini-tests lying under this test.
Maybe you can split the test into smaller ones?

2020-05-25 16:38 UTC, YaronWittenstein commented on examples/counter/counter.go
> +	// TODO: add on-the-fly wat2wasm translation
maybe we can add `is_wast` to the SVM interface.
What do you think?

2020-05-25 16:38 UTC, YaronWittenstein commented on examples/counter/counter.go
> +
you need to release the `deployTemplateResult`

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/commands.go
> +
I think you need to add:

```go
func (r DeployTemplateResult) Free() string {
  // free `Receipt`
  // free `TemplateAddr`
}
```

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/commands.go
> +
I think you need to add:

```go
func (r SpawnAppResult) Free() string {
  // free `Receipt`
  // free `InitialState`
  // free `AppAddr`
}
```

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/commands.go
> +
I think you need to add:

```go
func (r ExecAppResult) Free() string {
  // free `Receipt`
  // free `NewState `
  // free `Returns`
}
```

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/cgo_ext_test.go
> +	for i, b := range slice {
it seems you can extract repetitive code like:

```go
unsafe.Pointer(uintptr(unsafe.Pointer(goSliceCloneHeader.Data)) + i)
```

into a helper function

2020-05-25 16:38 UTC, YaronWittenstein commented on examples/counter/counter.go
> +
```go
deployTemplateResult.Free()
```

2020-05-25 16:38 UTC, YaronWittenstein commented on examples/counter/counter.go
> +
```go
spawnAppResult.Free()
```

2020-05-25 16:38 UTC, YaronWittenstein commented on examples/counter/counter.go
> +
```go
execAppResult.Free()
```

2020-05-25 16:38 UTC, YaronWittenstein commented on examples/counter/counter.go
> +
```
execAppResult.Free()
```

2020-05-25 16:38 UTC, YaronWittenstein commented on examples/counter/counter.go
> +}
```go
execAppResult.Free()
```

2020-05-25 16:38 UTC, YaronWittenstein commented on examples/counter/counter.go
> +	noError(err)
there is a free kv in another PR branch:
https://github.com/spacemeshos/svm/blob/8bd54e6009f9f5e1ea1831e4f8a74626f098f4b8/crates/svm-runtime-c-api/src/api.rs#L359

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/address.go
> +package svm
I think we'll need also: `svm/state.go` file
with 

```go
const StateLen = 32

...
```

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/import.go
> +	wasmInputs = make(ValueTypes, inputArity)
I'd rename to `funcArgs` instead of `wasmInputs`

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/import.go
> +	wasmOutputs = make(ValueTypes, outputArity)
I'd renamee `funcReturns` (or `funcRets`) instead of `wasmOutputs`

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/validation.go
> +func ValidateAppTx(runtime Runtime, appTx []byte) (Address, error) {
There are validation methods for `deploy-template` and `spawn-app` too:
https://github.com/spacemeshos/svm/blob/8bd54e6009f9f5e1ea1831e4f8a74626f098f4b8/crates/svm-runtime-c-api/src/api.rs#L83-L119

2020-05-25 16:38 UTC, YaronWittenstein commented on svm/value_test.go
> +func TestValues_Encode_Decode(t *testing.T) {
I'd rather have a few smaller tests instead of one testing all cases

2020-05-25 18:34 UTC, YaronWittenstein requested changes

2020-05-25 18:34 UTC, YaronWittenstein commented on svm/bridge.go
> +func cSvmTemplateReceiptAddr(receipt []byte) (Address, error) {
I think it would be better to keep the raw Receipt generated via SVM.
Otherwise, we end up building `cReceipt` for each Receipt helper

2020-06-08 10:45 UTC, moshababo commented on README.md
> +To allow direct and seamless import of the Go package, it includes the pre-compiled binaries mentioned above, which will be continuously updated. It *currently* supports only macOS x86_64.
As discussed, I think we should should use the published artifacts with the ability to locally compile `svm`, but the artifacts should be stored anyway. It will be handled in the next PR.

2020-06-08 10:53 UTC, moshababo commented on examples/counter/counter.go
> +// The first argument is the runtime context, and must be included by all import functions.
I'm not sure about that, and we actually verify this param on the Go side (following wasmer Go bindings, here: https://github.com/wasmerio/go-ext-wasm/blob/master/wasmer/import.go#L201).

2020-06-08 10:55 UTC, moshababo commented on examples/counter/counter.go
> +	pageCount int,
I'll upgrade SVM version in a consecutive PR.

2020-06-08 15:49 UTC, moshababo commented on svm/host_ctx.go
> +	panic("not implemented")
AFAIK the encoding scheme for `hostCtx` KV wasn't defined yet.

2020-06-08 15:56 UTC, moshababo commented on svm/kv.go
> +func NewMemoryKVStore() (unsafe.Pointer, error) {
Will be removed once SVM version will be upgraded.

2020-06-08 16:02 UTC, moshababo commented on examples/counter/counter.go
> +	// TODO: add on-the-fly wat2wasm translation
Sounds good.

2020-06-08 17:49 UTC, moshababo commented on examples/counter/counter.go
> +	// TODO: add on-the-fly wat2wasm translation
Can you open an issue under `svm` repo?

2020-06-08 18:19 UTC, moshababo commented on examples/counter/counter.go
> +	noError(err)
Will be added once upgrading SVM version.

2020-06-08 18:19 UTC, moshababo commented on svm/validation.go
> +func ValidateAppTx(runtime Runtime, appTx []byte) (Address, error) {
Will be added once upgrading SVM version.

2020-06-08 18:26 UTC, moshababo commented on svm/bridge.go
> +func cSvmTemplateReceiptAddr(receipt []byte) (Address, error) {
There's definitely room for many optimizations in memory management, but I rather keep things safe/simple for now, and apply them once we know the actual usage patterns.

2020-06-08 19:16 UTC, moshababo commented on svm/address.go
> +package svm
I'm not sure where this should be defined (whether in `go-svm` or `go-spacemesh`), so I rather wait with this for now, and just keep handling state as []byte slice.

2020-06-11 07:08 UTC, YaronWittenstein approved these changes
@moshababo 
Good job!

2020-06-11 07:08 UTC, YaronWittenstein commented on svm/host_ctx.go
> +	panic("not implemented")
It's been implemented here:
https://github.com/spacemeshos/svm/blob/812abb895b4e09f0d14c3d7b09c2fc2dad920699/crates/svm-app/src/raw/host_ctx/mod.rs

It's OK if it will be added in a future PR

2020-06-11 07:26 UTC, merged